In [20]:
import pandas as pd
import numpy as np
import sklearn

In [7]:
train_x = pd.read_csv("train_x.csv")#train_data読み込み
train_y = pd.read_csv('train_y.csv')

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (114) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [21]:
train_y.columns

Index(['お仕事No.', '応募数 合計'], dtype='object')

In [23]:
train_y1 = train_y["応募数 合計"]
train_y1.head()

0    1.945910
1    3.951244
2    3.295837
3    3.970292
4    3.784190
Name: 応募数 合計, dtype: float64

In [24]:
y1_train =np.array(train_y1)#目的変数変換
y1_train = y1_train.reshape(-1,1)
y1_train

array([[1.94591015],
       [3.95124372],
       [3.29583687],
       ...,
       [0.        ],
       [0.69314718],
       [0.        ]])

In [11]:
train_x6 = train_x["残業月20時間以上"]

In [12]:
X6_train = np.array(train_x6)
X6_train = X6_train.reshape(-1,1)

In [13]:
X6_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [15]:
from sklearn.linear_model import Lasso

In [16]:
lasso  = Lasso()

In [17]:
lasso.fit(X6_train,y1_train)

Lasso()

In [26]:
test_x = pd.read_csv("test_x.csv")

In [27]:
test_x6 = test_x["残業月20時間以上"]

In [36]:
X6_test = np.array(test_x6)
X6_test = X6_test.reshape(-1,1)

In [37]:
y_pred = lasso.predict(X6_test)
y_pred

array([0.54224691, 0.54224691, 0.54224691, ..., 0.54224691, 0.54224691,
       0.54224691])

In [42]:
test_y3 =pd.DataFrame()

In [43]:
test_y3["お仕事No."] =test_x["お仕事No."]

In [44]:
test_y3["応募数 合計"] = y_pred

In [45]:
test_y3.head()

お仕事No.    応募数 合計
0  2203556553  0.542247
1  2203515280  0.542247
2  2203546900  0.542247
3  2203545344  0.542247
4  2203557987  0.542247

In [46]:
test_y3.to_csv("test_y3.csv", index=False)